Attribute VB_Name = "CampgroundModule"
Public SBCTR As Integer
Public TCTR As Integer
Public RJCTR As Integer
Public XJCTR As Integer
Public MKCTR As Integer
Public SleepingBag As Single
Public Tent As Single
Public RegJacket As Single
Public XXLJacket As Single
Public MessKit As Single
Public SleepingBagSub As Single
Public TentSub As Single
Public JacketSub As Single
Public MessKitSub As Single
Public Subtotal As Single
Public GrandTotal As Single
